lawn_stats/urls.py
from django.urls import path

from . import views

app_name = "lawn_stats"

urlpatterns = [
    path("upload_csv/", views.upload_csv, name="upload_csv"),
    path("map_columns/", views.map_columns, name="map_columns"),
    path("upload_afat_data/", views.upload_afat_data, name="upload_afat_data"),
    path("creator_charts/", views.creator_charts, name="creator_charts"),
    path("all_charts/", views.all_charts, name="all_charts"),
]

lawn_stats/templates/lawn_stats/base.html
{% extends 'allianceauth/base-bs5.html' %}

{% load i18n %}

{% block page_title %}
    {% translate "Lawn Stats" %}
{% endblock %}

{% block header_nav_brand %}
    {% translate "Lawn Stats" %}
{% endblock header_nav_brand %}

{% block header_nav_collapse_left %}
    {% include "lawn_stats/partials/top_menu.html" %}
{% endblock %}

{% block content %}
    <div class="allianceauth-lawn-stats">
        {% block lawn_stats_body %}{% endblock %}
    </div>
{% endblock %}

lawn_stats/templates/lawn_stats/base_charts.html
{% extends 'lawn_stats/base.html' %}

{% load i18n %}
{% load humanize %}

{% block lawn_stats_body %}
<div class="container mt-3">
    <div class="text-center mb-3">
        <h2>Alliance Auth Charts</h2>
    </div>
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div class="month-year-selector">
            <a href="?prev_month=true&month={{ month }}&year={{ year }}" class="btn btn-secondary">
                <i class="fa-solid fa-backward"></i>
            </a>
            <span class="mx-2">{{ selected_month }} {{ selected_year }}</span>
            {% if show_forward %}
                <a href="?next_month=true&month={{ month }}&year={{ year }}" class="btn btn-secondary">
                    <i class="fa-solid fa-forward"></i>
                </a>
                <a href="?next_to_current=true" class="btn btn-secondary">
                    <i class="fa-solid fa-fast-forward"></i>
                </a>
            {% endif %}
        </div>
    </div>
    <ul class="nav nav-tabs w-100" id="chartTabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="creator-charts-tab" data-bs-toggle="tab" href="#creator-charts" role="tab" aria-controls="creator-charts" aria-selected="true">FC Charts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="alliance-charts-tab" data-bs-toggle="tab" href="#alliance-charts" role="tab" aria-controls="alliance-charts" aria-selected="false">Alliance Charts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="corp-charts-tab" data-bs-toggle="tab" href="#corp-charts" role="tab" aria-controls="corp-charts" aria-selected="false">Corp Charts</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="raw-data-tab" data-bs-toggle="tab" href="#raw-data" role="tab" aria-controls="raw-data" aria-selected="false">Raw Data</a>
        </li>
    </ul>
    <div class="tab-content w-100" id="chartTabsContent">
        <div class="tab-pane fade show active" id="creator-charts" role="tabpanel" aria-labelledby="creator-charts-tab">
            {% include 'lawn_stats/charts/creator_charts.html' %}
        </div>
        <div class="tab-pane fade" id="alliance-charts" role="tabpanel" aria-labelledby="alliance-charts-tab">
            {% include 'lawn_stats/charts/alliance_charts.html' %}
        </div>
        <div class="tab-pane fade" id="corp-charts" role="tabpanel" aria-labelledby="corp-charts-tab">
            {% include 'lawn_stats/charts/corp_charts.html' %}
        </div>
        <div class="tab-pane fade" id="raw-data" role="tabpanel" aria-labelledby="raw-data-tab">
            {% include 'lawn_stats/charts/raw_data.html' %}
        </div>
    </div>
</div>
{% endblock %}

lawn_stats/templates/lawn_stats/map_columns.html
<!-- templates/map_columns.html -->

{% load static %}
{% load form_filters %}

<!DOCTYPE html>
<html>
<head>
    <title>Column Mapping</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }
        .form-row label {
            flex: 1;
            text-align: left;  /* Align labels to the left */
            margin-right: 10px;  /* Add some space between label and input */
        }
        .form-row .form-control {
            flex: 2;
            max-width: 300px;  /* Adjust the max-width as needed */
        }
        .form-row .form-check {
            margin-left: 10px;
        }
        .form-container {
            display: flex;
            flex-direction: column;
            align-items: flex-start;  /* Align the entire form container to the left */
        }
    </style>
</head>
<body>
<div class="container">
    <h2>Map Columns</h2>
    <div class="form-container">
        <form method="post" action="{% url 'lawn_stats:map_columns' %}">
            {% csrf_token %}
            {% for column in columns %}
                <div class="form-row">
                    <label for="{{ form|get_field:column|get_field_id }}">{{ column }}</label>
                    {{ form|get_field:column }}
                    <div class="form-check">
                        {{ form|get_ignore_field:column }}
                        <label class="form-check-label" for="{{ form|get_ignore_field:column|get_field_id }}">Ignore</label>
                    </div>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

lawn_stats/templates/lawn_stats/month_year_selector.html
<form method="GET" action="{% url 'lawn_stats:all_charts' %}" class="d-flex justify-content-center align-items-center">
    <button type="submit" name="prev_year" class="btn btn-primary">&laquo;</button>
    <button type="submit" name="prev_month" class="btn btn-primary">&lsaquo;</button>
    <span class="mx-3">{{ selected_month }} {{ selected_year }}</span>
    <button type="submit" name="next_month" class="btn btn-primary">&rsaquo;</button>
    <button type="submit" name="next_year" class="btn btn-primary">&raquo;</button>
    <input type="hidden" name="month" value="{{ month }}">
    <input type="hidden" name="year" value="{{ year }}">
</form>

lawn_stats/templates/lawn_stats/upload_afat_data.html
<!-- templates/upload_afat_data.html -->

{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Upload AFAT Data</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
    <h2>Upload AFAT Data</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

lawn_stats/templates/lawn_stats/upload_csv.html
<!-- templates/upload_csv.html -->

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>